### ISSUE TITLE
checkbox

### ISSUE THREAD

**Issue by guer0125** [guer0125/volunteer-form#1]
Hi there, im doing the last form assignment @muxlowc

I need help with how to arrange the checklist, i'm not able to align them, also i'm not sure why my bold doesn't look as bold as the sample.

Thank you

**Comment by muxlowc** [comment]
@guer0125  

1) you have an extra " on line 25: make sure you delete that extra quote after pad-b-1-8

2) You're going to have to use a grid/units to get your checkboxes side my side.. here's a bit to get you started:
```
<div class="grid">
          <div class="unit xs-1 s-1 m-1-2 l-1-2 gutter-1-2">
            <div class="pad-t-1-8 pad-b-1-8">
              <input type="checkbox" id="digging-holes">
              <label for="digging-holes">Digging holes</label>
            </div>
```

**Comment by guer0125** [comment]
Hi there, 

1.my bold for the header is still no as bold as the sample. 

2. how do i do the (option) italic green

3.`Your full legal name, for insurance purposes, e.g. Elizabeth Bradley` is bolder on mine and not on the sample. i tried .normal and .not-bold but stays the same 

4. markbot is asking for an `hr` which i thought goes before `e.g Elizabeth` but i'm not allowed to put it inside a <p> tag and for some reason it gives me a line between the two which i don't know how to get rid of

5. markbot won't allow me to place a `h2` first thing after a fieldset but it is the only way i see a line in between the fieldset. if i use a legend and don't get a line do i just make a bottom border?

6.`Do you have a valid driver's licence` I can't seem to be able to move it down

thank you,

**Comment by muxlowc** [comment]
@guer0125 

1) Don't worry about the boldness of the H1 - these will look different from browser to browser, screen to screen (Thomas made these a while ago, so his looks different)

It does look like you have the wrong font though, it should be:
 ` <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700" rel="stylesheet">`

css:
html {
  font-family: "Droid Serif", serif;
}

2) you can simply put "optional" into an `<em>` and add a class / change it's color in the css
3) code above should fix this

4) There should be an `<hr>` between each fieldset
```
      <div class="gutter-1-2">
        <hr class="push-2">
      </div>
```
You actually also have to add the below to your css:
fieldset {
  border: 0;
}

(so rather than using the border from the fieldset, we want to hide the fieldset border, and add in HR tags between each section - we do this just because we want the borders to look different than what they normally generate)

5) You need to put "Personal Details" inside of a `<legend>` and not an H2

**Comment by guer0125** [comment]
Hi again :)

1. how do i space out the radios between yes and no?

2. bottom textarea larger for `Please let us know any comments or questions you may have (optional)`?

3.marbot is saying the `action` attribute on a `form` tag mush point somewhere but on the assignment it says "The form does not need to submit to Formspree." so are these two different things?

4. I kept the ['html', 'font-family', '"Noto Serif", serif'] because that's the one markbot says although i do feel it looks a bit different in the screenshots

i really only need to go down 1% on 320px screen to submit

thanks again
